receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch: {}
  cumulativetodelta: {}
exporters:
  otlphttp:
    endpoint: xxx
    headers:
      Authorization: xxx
service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - otlphttp
    metrics:
      receivers:
      - otlp
      processors:
      - cumulativetodelta
      - batch
      exporters:
      - otlphttp
    logs:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - otlphttp
